require:
  - "rubocop-minitest"
  - "rubocop-performance"
  - "rubocop-rake"

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Max: 120
  Exclude: 
    - "test/**/*.rb"
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
Naming/MethodParameterName:
  Enabled: false
Naming/FileName:
  Exclude:
    - "src/*-*.rb"

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 25
Lint/RedundantCopDisableDirective:
  Exclude: 
    - "test/**/*.rb"
Metrics/BlockLength:
  Exclude: 
    - "test/**/*.rb"
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 12
Metrics/MethodLength:
  Exclude: 
    - "test/**/*.rb"

AllCops:
  NewCops: enable
