#!/usr/bin/env bash

builtin source "${BASH_SOURCE[0]%/*}"/../lib/init.sh

main() {
	[[ ${EUID:-} -eq 0 ]] || abort "Run with sudo"

	if [[ "$(</proc/sys/kernel/osrelease)" == *Microsoft ]]; then # WSL
		doing Installing system dependencies under WSL

		local debs=() gems=()

		builtin type -P ruby &>/dev/null || debs+=(ruby-all-dev)
		builtin type -P git  &>/dev/null || debs+=(git)
		builtin type -P curl &>/dev/null || debs+=(curl)

		builtin type -P bundle &>/dev/null || gems+=(bundler)

		if [[ ${#debs[@]} -gt 0 ]]; then
			command -v apt-get &>/dev/null || abort "Only Debian and derivatives (e.g. Ubuntu) supported"
			apt-get -y update && apt-get -y install "${debs[@]}"
		fi

		if [[ ${#gems[@]} -gt 0 ]]; then
			gem install "${gems[@]}"
		fi

		[[ ! -x .local/libexec/boot/wsl ]] || .local/libexec/boot/wsl
	elif command -v apt-get &>/dev/null && [[ -x .local/libexec/boot/debian ]]; then
		doing Installing system dependencies

		.local/libexec/boot/debian
	fi
}

main "$@"
