#!/usr/bin/env bash

builtin source "${BASH_SOURCE[0]%/*}"/../lib/init.sh

main() {
	[[ ${EUID:-} -ne 0                          ]] || abort "Run without root permissions (avoid using sudo)"
	[[ ! -x "${BASH_SOURCE[0]%/*}"/sysboot      ]] || sudo "${BASH_SOURCE[0]%/*}"/sysboot
	[[ ! -x "${BASH_SOURCE[0]%/*}"/../bin/setup ]] || "${BASH_SOURCE[0]%/*}"/../bin/setup
}

main "$@"
